config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :enrollments
  resources :students
  resources :instructors

  Rails.application.routes.draw do
    # ...
    post '/create_user' => 'instructors#create_user'
  end
  Rails.application.routes.draw do
    # ...
    post '/create_student' => 'students#create_student'
    post '/edit_user' => 'instructors#edit_user'
    post '/edit_student' => 'students#edit_student'
    post '/edit_admin' => 'instructors#edit_admin'
  end


  """devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end"""
  #devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users, controllers: { sessions: "sessions" }
  resources :courses
  #get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user
    has_many :enrollments
    has_many :waitlists, dependent: :destroy
    validates_presence_of :dob, :phone, :major
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # This function ensures that an student cannot edit/destroy any other student's course.
  # The student details can only be edited/deleted by the corresponding student and admin.
  def correct_user
    get_id
    if @userid!=@student.id && current_user.user_type!='Admin'
      redirect_to courses_path, notice: "Not authorized to edit/delete this Profile."
    end
  end

  # This function is used to edit the student details
  def edit_student
    name = params['name']
    email = params['email']
    pass = params['password']
    dob = params['dob']
    major = params['major']
    phone = params['phone']
    id = params['id']

    user = User.find_by(id: Student.find_by(id: id).user_id)
    uid = User.find_by(id: Student.find_by(id: id).user_id).id

    h = {:name => name, :email => email, :password => pass, :user_type => "Student"}
    user.update(h)

    ins = Student.find_by(id: id)
    ins.update({:major => major, :dob => dob, :phone => phone})
    
    redirect_to students_path(:flag => {:flag_val => '0'}), notice:"Student updated successfully"
  end

  #Used to create the student 
  def create_student
    name = params['name']
    email = params['email']
    pass = params['password']
    dob = params['dob']
    phone = params['phone']
    major = params['major']

    user = User.new
    user.name = name
    user.email = email
    user.password = pass
    user.user_type = 'Student'
    user.sign_in_count = 1
    user.save!
    
    user = User.find_by(email: email).id
    stud = Student.new
    stud.dob = dob
    stud.phone = phone
    stud.major = major
    stud.user_id = user

    stud.save!
    redirect_to students_path(:flag => {:flag_val => '0'})

  end

  # GET /students or /students.json
  def index
    @f = params[:flag]
    if @f[:flag_val]=='0'
      @students = Student.all
    else
      @par = params[:c_id]
      @par2 = params[:waitlist]
      enrollments = Enrollment.where(course_id: @par[:course_id])
      waitlists = Waitlist.where(course_id: @par[:course_id])
      l = []
      enrollments.each do |enrollment|
        l.append(enrollment.student_id)
      end
      waitlists.each do |waitlist|
        l.append(waitlist.student_id)
      end
      @students = []
      temp = Student.all
      temp.each do |i|
        if l.include?(i.id) == false
          @students.append(i)
        end
      end
    end
  end

  # GET /students/1 or /students/1.json
  def show
    @user = @student.user_id
    @user = User.find_by(id:@user)
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @user_record = User.find(@student.user_id)
    @user_record.destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url(:flag => {:flag_val => '0'}), notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:dob, :phone, :major, :c_id, :flag, :waitlist)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<% if user_signed_in? && current_user.user_type=="Admin" %>

  <form method="post" action="/create_student">

      <label>Name</label>
      <input name="name" type="text" required/>
      <br /> <br />

      <label>Email</label>
      <input name="email" type = "text" required>
      <br /> <br />

      <label>Password</label>
      <input name="password" type="password" required/>
      <br /> <br />

      <label>DOB</label>
      <input name="dob" type="date" pattern = "^(0[1-9]|1[012])[-/.](0[1-9]|[12][0-9]|3[01])[-/.](19|20)\\d\\d$" required/>
      <br /> <br />

      <label>Phone</label>
      <input name="phone" type="tel" placeholder = "XXXXXXXXXX" pattern = "^\d{10}$" required/>
      <br /> <br />

      <label>Major</label>
      <input name="major" type="text" required/>
      <br /> <br />

      <input type="submit" value="Create Student" />

    </form>

<% else %>

  <%= form_with(model: student) do |form| %>
    <% if student.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

        <ul>
          <% student.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :dob, style: "display: block" %>
      <%= form.text_field :dob %>
    </div>

    <div>
      <%= form.label :phone, style: "display: block" %>
      <%= form.text_field :phone %>
    </div>

    <div>
      <%= form.label :major, style: "display: block" %>
      <%= form.text_field :major %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Dob:</strong>
    <%= student.dob %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= student.phone %>
  </p>

  <p>
    <strong>Major:</strong>
    <%= student.major %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing Student</h1>
<% if user_signed_in? && current_user.user_type=="Admin" %>

  <form method="post" action="/edit_student">

    <label>Name</label>
    <input name="name" type="text" required/>
    <br /> <br />

    <label>Email</label>
    <input name="email" type = "text" required>
    <br /> <br />

    <label>Password</label>
    <input name="password" type="password" required/>
    <br /> <br />

    <label>Date of Birth</label>
    <input name="dob" type="text" required/>
    <br /> <br />

    <label>Phone number</label>
    <input name="phone" type="text" required/>
    <br /> <br />

    <label>Major</label>
    <input name="major" type="text" required/>
    <br /> <br />

    <input type = "hidden" name='id' type='text' value=<%= @student.id %> > <br>

    <input type="submit" value="Update User" />

  </form>

  <br>

  <div>
    <%= link_to "Show this student", @student %> |
    <%= link_to "Back to students", students_path(:flag => {:flag_val => '0'}) %>
  </div>
<% else %>
  <%= render "form", student: @student %>
<% end %>

app/views/students/index.html.erb
<h2>Students list </h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>   
      <th scope="col">Name</th> 
      <th scope="col">Phone</th>
      <th scope="col"> Major</th>
      <th scope="col">View</th>
      <% if @f[:flag_val]!='0' %>
        <th scope="col"> Enroll? </th>
      <% end %>
    </tr>
  </thead>
    
  <% @students.each do |sub| %>
    <tbody>
        <tr>
          <td><%= sub.id %></td>
          <td><%= User.find(Student.find(sub.id).user_id).name %> </td>
          <td><%= sub.phone %></td>
          <td><%= sub.major %></td>
          <td><%= link_to "Show this student", sub %> </td>
          <% if @f[:flag_val]!='0' %>
            <% if @par2[:wl]!='1' %>
              <td><%= link_to "Enroll", new_enrollment_path(:enroll => {:course_id => @par[:course_id],:student_id => sub.id}) %></td>
            <% else %>
              <td><%= link_to "Enroll", new_waitlist_path(:enroll => {:course_id => @par[:course_id],:student_id => sub.id}) %></td>
            <% end %>
          <%end%>
        </tr>
    </tbody>
  <% end %>
</table>
<% if @f[:flag_val]=='0' %>
  <%= link_to "New student", new_student_path %>
<% end %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path{:flag_val => '0'} %>
</div>

app/views/students/show.html.erb
<b>Name:</b> <%= @user.name %> <br>
<b>Email:</b> <%= @user.email %> <br>

<%= render @student %>
<%if current_user.user_type!='Instructor' && current_user.user_type!='Student' %>

  <div>
    <%= link_to "Edit this student", edit_student_path(@student) %> |
    <%= link_to "Back to students", students_path(:flag => {:flag_val => '0'}) %>

    <%= button_to "Destroy this student", @student, method: :delete %>
  </div>

<% end %>