config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :enrollments
  resources :students
  resources :instructors

  Rails.application.routes.draw do
    # ...
    post '/create_user' => 'instructors#create_user'
  end
  Rails.application.routes.draw do
    # ...
    post '/create_student' => 'students#create_student'
    post '/edit_user' => 'instructors#edit_user'
    post '/edit_student' => 'students#edit_student'
    post '/edit_admin' => 'instructors#edit_admin'
  end


  """devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end"""
  #devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users, controllers: { sessions: "sessions" }
  resources :courses
  #get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_many :courses, dependent: :destroy
    belongs_to :user
    validates_presence_of :department
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # This function ensures that an instructor cannot edit/destroy any other profile
  def correct_user
    get_id
    if current_user.user_type!='Admin' && @userid!=@instructor.id
      redirect_to courses_path, notice: "Not authorized to edit/delete this Profile."
    end
  end

  # Used to update admin details.
  def edit_admin
    name = params['name']
    phone = params['phone']

    user = User.find_by(user_type: "Admin")
    ad = Admin.find_by(user_id: user.id)

    user.update({:name => name})
    ad.update({:phone => phone})

    redirect_to courses_path, notice: "Admin Successfully Updated"
  end

  #used to update instructor details.
  def edit_user
    name = params['name']
    email = params['email']
    pass = params['password']
    dep = params['department']
    id = params['id']

    user = User.find_by(id: Instructor.find_by(id: id).user_id)
    uid = User.find_by(id: Instructor.find_by(id: id).user_id).id

    h = {:name => name, :email => email, :password => pass, :user_type => "Instructor"}
    user.update(h)
    
    ins = Instructor.find_by(id: id)
    ins.update({:department => dep})
    
    redirect_to instructors_path, notice:"Instructor updated successfully"
  end

  # used to create a new user as intructor and redirect to the instructors path.
  def create_user
    name = params['name']
    email = params['email']
    pass = params['password']
    dep = params['department']

    user = User.new
    user.name = name
    user.email = email
    user.password = pass
    user.user_type = 'Instructor'
    user.sign_in_count = 1
    user.save!
    
    user = User.find_by(email: email).id
    ins = Instructor.new
    ins.department = dep
    ins.user_id = user
    
    ins.save!

    redirect_to instructors_path

  end

  # GET /instructors or /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1 or /instructors/1.json
  def show
    @user = @instructor.user_id
    @user = User.find_by(id:@user)
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors or /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to instructor_url(@instructor), notice: "Instructor was successfully created." }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1 or /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to instructor_url(@instructor), notice: "Instructor was successfully updated." }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1 or /instructors/1.json
  def destroy
    @user_record = User.find(@instructor.user_id)
    @user_record.destroy
    @instructor.destroy

    respond_to do |format|
      format.html { redirect_to instructors_url, notice: "Instructor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      if params[:id]!='0'
        @instructor = Instructor.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def instructor_params
      params.require(:instructor).permit(:department)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<% if user_signed_in? && current_user.user_type=="Admin" %>

  <form method="post" action="/create_user">

      <label>Name</label>
      <input name="name" type="text" required/>
      <br /> <br />

      <label>Email</label>
      <input name="email" type = "text" required>
      <br /> <br />

      <label>Password</label>
      <input name="password" type="password" required/>
      <br /> <br />

      <label>Department</label>
      <input name="department" type="text" required/>
      <br /> <br />

      <input type="submit" value="Create User" />

    </form>

<% else %>
  <%= form_with(model: instructor) do |form| %>
    <% if instructor.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

        <ul>
          <% instructor.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :department, style: "display: block" %>
      <%= form.text_field :department %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/instructors/_instructor.html.erb
<div id="<%= dom_id instructor %>">
  <p>
    <strong>Department:</strong>
    <%= instructor.department %>
  </p>

</div>

app/views/instructors/edit.html.erb
<% if current_user.user_type=="Admin" && !@instructor %>
  <h1>Editing Admin</h1>
    <form method="post" action="/edit_admin">

    <label>Name</label>
    <input name="name" type="text" value = <%= current_user.name %> required/>
    <br /> <br />

    <label>Email</label>
    <input name="email" type = "text" value = "admin@ncsu.edu" readonly>
    <br /> <br />

    <label>Password</label>
    <input name="password" type="text" value = "admin123" readonly/>
    <br /> <br />

    <label>Phone</label>
    <input name="phone" type="text" value = <%= Admin.find_by(user_id: current_user.id).phone %> required/>
    <br /> <br />

    <input type="submit" value="Update Profile" />

  </form>

<% else %>
  <h1>Editing instructor</h1>
  <% if user_signed_in? && current_user.user_type=="Admin" %>

    <form method="post" action="/edit_user">

      <label>Name</label>
      <input name="name" type="text" required/>
      <br /> <br />

      <label>Email</label>
      <input name="email" type = "text" required>
      <br /> <br />

      <label>Password</label>
      <input name="password" type="password" required/>
      <br /> <br />

      <label>Department</label>
      <input name="department" type="text" required/>
      <br /> <br />

      <input type = "hidden" name='id' type='text' value=<%= @instructor.id %> > <br>

      <input type="submit" value="Update User" />

    </form>

    <br>

    <div>
      <%= link_to "Show this instructor", @instructor %> |
      <%= link_to "Back to instructors", instructors_path %>
    </div>

  <% else %>
    <%= render "form", instructor: @instructor %>
  <% end %>
<% end %>

app/views/instructors/index.html.erb
<h2>All Instructors </h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>   
      <th scope="col">Name</th>
      <th scope="col">Email</th> 
      <th scope="col"> Department </th>
      <th scope="col"> View </th>
      <th scope="col"> Add a course </th>

    </tr>
  </thead>
    
  <% @instructors.each do |sub| %>
    <tbody>
        <tr>
          <td><%= sub.id %></td>
          <td><%= User.find(Instructor.find(sub.id).user_id).name %> </td>
          <td><%= User.find(Instructor.find(sub.id).user_id).email %></td>
          <td><%= sub.department %></td>
          <td><%= link_to "Show this instructor", sub %> </td>
          <td><%= link_to "Add a course", new_course_path(:ins => {:ins_id => sub.id}) %> </td>
          
        </tr>
    </tbody>
  <% end %>
</table>

<%= link_to "New instructor", new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New instructor</h1>

<%= render "form", instructor: @instructor %>

<br>

<div>
  <%= link_to "Back to instructors", instructors_path %>
</div>

app/views/instructors/show.html.erb
<b>Name:</b> <%= @user.name %> <br>
<b>Email:</b> <%= @user.email %>
<%= render @instructor %>
<%if current_user.user_type!='Instructor' && current_user.user_type!='Student' %>
  <div>
    <%= link_to "Edit this instructor", edit_instructor_path(@instructor) %> |
    <%= link_to "Back to instructors", instructors_path %>

    <%= button_to "Destroy this instructor", @instructor, method: :delete %>
  </div>
<% end %>