config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :enrollments
  resources :students
  resources :instructors

  Rails.application.routes.draw do
    # ...
    post '/create_user' => 'instructors#create_user'
  end
  Rails.application.routes.draw do
    # ...
    post '/create_student' => 'students#create_student'
    post '/edit_user' => 'instructors#edit_user'
    post '/edit_student' => 'students#edit_student'
    post '/edit_admin' => 'instructors#edit_admin'
  end


  """devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end"""
  #devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users, controllers: { sessions: "sessions" }
  resources :courses
  #get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  #Checks if the user has signed in for the first time and redirects it to respective paths for Instructors and Students
  def index
    if current_user.user_type=="Instructor"
      ins = Instructor.new
      ins.department = 'Computer Science'
      ins.user_id = current_user.id
      current_user.sign_in_count = 1
      ins.save!
      current_user.save!
      redirect_to edit_instructor_path(ins.id)
    elsif current_user.user_type=="Student"
      std = Student.new
      std.dob = '10/10/2022'
      std.phone = '9193214567'
      std.major = 'Computer Science'
      std.user_id = current_user.id
      current_user.sign_in_count = 1
      std.save!
      current_user.save!
      redirect_to edit_student_path(std.id)
    end
  end
  

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark thead-dark">
  <div class="container-fluid">
    <%= link_to 'Student Enrollment System', courses_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
       
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to 'Show courses', courses_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Show enrollments', enrollments_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Show waitlists', waitlists_path, class:"nav-link" %>
          </li>
          <% if current_user.user_type == "Instructor" %>
            <li class="nav-item">
              <%= link_to 'Edit Profile', edit_instructor_path(Instructor.find_by(user_id: current_user.id).id), class:"nav-link" %>
            </li>
          <% elsif current_user.user_type == "Student" %>
            <li class="nav-item">
              <%= link_to 'Edit Profile', edit_student_path(Student.find_by(user_id: current_user.id).id), class:"nav-link" %>
            </li>
          <% end %>
          <% if current_user.user_type == "Admin" %>
            <li class="nav-item">
              <%= link_to 'Show Students', students_path(:c_id => {:course_id => -1}, :flag => {:flag_val => '0'}), class:"nav-link" %>
            </li>  
            <li class="nav-item">
              <%= link_to 'Show Instructors', instructors_path, class:"nav-link" %>
            </li>  
            <li class="nav-item">
              <%= link_to 'Edit Profile', edit_instructor_path('0'), class:"nav-link" %>
            </li> 
          <% end %>            
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>                
      </ul>

      <ul class="navbar-nav navbar-brand ml-auto mb-5 mb-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
        Welcome <%= current_user.name %>
        <% if current_user.user_type=="Student" %>
        , Role: <b><%= current_user.user_type %></b>
        <% elsif current_user.user_type=="Instructor"%>
        , Role: <b><i><%= current_user.user_type%></i></b>
        <% else %>
        , Role: <u><%= current_user.user_type%></u>
        <% end %>
        
        
        </li>
      <% end %> 
      </ul>

    </div>
  </div>
</nav>